'use client'

import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'hi' | 'ta' | 'te' | 'ml' | 'kn' | 'mr' | 'gu'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  return (
    <LanguageContext.Provider value={{ language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

// Translation dictionary
export const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    jobs: 'Jobs',
    profile: 'Profile',
    translate: 'AI Translator',
    home: 'Home',
    features: 'Features',
    about: 'About',
    logout: 'Logout',
    login: 'Login',
    signup: 'Sign Up',
    bridgehire: 'BridgeHire',
    searchJobs: 'Search Jobs',
    jobTitle: 'Job Title',
    location: 'Location',
    jobType: 'Job Type',
    experience: 'Experience Required',
    filter: 'Filter',
    applyNow: 'Apply Now',
    saved: 'Saved',
    saveJob: 'Save Job',
    unsaveJob: 'Unsave Job',
    matchScore: 'Match Score',
    verifiedJob: 'Verified Job',
    learnMore: 'Learn More',
    exploreJobs: 'Explore Jobs',
    postJob: 'Post Job',
    viewProfile: 'View Profile',
    editProfile: 'Edit Profile',
    myApplications: 'My Applications',
    languageNoBarrier: 'Language is No Barrier',
    translateDesc: 'Understand job descriptions, applications, and communications in your preferred language.',
    instantTranslation: 'Instant Translation',
    multiLanguage: 'Multi-Language',
    accurate: 'Accurate',
    aiPowered: 'AI-Powered',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    jobs: 'नौकरियाँ',
    profile: 'प्रोफ़ाइल',
    translate: 'एआई अनुवादक',
    home: 'होम',
    features: 'विशेषताएं',
    about: 'के बारे में',
    logout: 'लॉगआउट',
    login: 'लॉगिन करें',
    signup: 'साइन अप करें',
    bridgehire: 'ब्रिजहायर',
    searchJobs: 'नौकरियाँ खोजें',
    jobTitle: 'नौकरी का शीर्षक',
    location: 'स्थान',
    jobType: 'नौकरी का प्रकार',
    experience: 'आवश्यक अनुभव',
    filter: 'फ़िल्टर',
    applyNow: 'अभी आवेदन करें',
    saved: 'सहेजी गई',
    saveJob: 'नौकरी सहेजें',
    unsaveJob: 'नौकरी हटाएं',
    matchScore: 'मिलान स्कोर',
    verifiedJob: 'सत्यापित नौकरी',
    learnMore: 'और जानें',
    exploreJobs: 'नौकरियाँ देखें',
    postJob: 'नौकरी पोस्ट करें',
    viewProfile: 'प्रोफ़ाइल देखें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    myApplications: 'मेरे आवेदन',
    languageNoBarrier: 'भाषा कोई बाधा नहीं है',
    translateDesc: 'अपनी पसंदीदा भाषा में नौकरी के विवरण, आवेदन और संचार को समझें।',
    instantTranslation: 'तत्काल अनुवाद',
    multiLanguage: 'बहु-भाषा',
    accurate: 'सटीक',
    aiPowered: 'एआई द्वारा संचालित',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    jobs: 'வேலைகள்',
    profile: 'சுயவிவரம்',
    translate: 'AI மொழிபெயர்ப்பு',
    home: 'முகப்பு',
    features: 'அம்சங்கள்',
    about: 'பற்றி',
    logout: 'வெளியேறு',
    login: 'உள்நுழைக',
    signup: 'பதிவு செய்யவும்',
    bridgehire: 'பிரிட்ஜ்ஹயர்',
    searchJobs: 'வேலைகளைத் தேடுக',
    jobTitle: 'வேலைப்பெயர்',
    location: 'இருப்பிடம்',
    jobType: 'வேலை வகை',
    experience: 'தேவையான அனுபவம்',
    filter: 'வடிகட்டி',
    applyNow: 'இப்போது விண்ணப்பிக்க',
    saved: 'சேமிக்கப்பட்ட',
    saveJob: 'வேலையைச் சேமிக்க',
    unsaveJob: 'வேலையை அகற்று',
    matchScore: 'பொருத்தம் மதிப்பெண்',
    verifiedJob: 'சரிபார்க்கப்பட்ட வேலை',
    learnMore: 'மேலும் அறிய',
    exploreJobs: 'வேலைகளை ஆராயுங்கள்',
    postJob: 'வேலை இடுக',
    viewProfile: 'சுயவிவரத்தைக் காண்க',
    editProfile: 'சுயவிவரத்தை திருத்து',
    myApplications: 'என் விண்ணப்பங்கள்',
    languageNoBarrier: 'மொழி தடையல்ல',
    translateDesc: 'வேலைப்பெயர்ப்பு விளக்கங்கள், விண்ணப்பங்கள் மற்றும் தகவல்தொடர்பைக் உங்கள் விருப்ப மொழியில் புரிந்து கொள்ளுங்கள்.',
    instantTranslation: 'உடனடி மொழிபெயர்ப்பு',
    multiLanguage: 'பல மொழி',
    accurate: 'துல்லியமான',
    aiPowered: 'AI இதன் மூலம் চালিত',
  },
  te: {
    dashboard: 'డ్యాష్‌బోర్డ్',
    jobs: 'ఉద్యోగాలు',
    profile: 'ప్రొఫైల్',
    translate: 'AI అనువాదం',
    home: 'హోమ్',
    features: 'లక్షణాలు',
    about: 'గురించి',
    logout: 'లాగ్ అవుట్',
    login: 'లాగిన్ చేయండి',
    signup: 'సైన్ అప్ చేయండి',
    bridgehire: 'బ్రిడ్జ్‌హైర్',
    searchJobs: 'ఉద్యోగాలను వెతకండి',
    jobTitle: 'ఉద్యోగం శీర్షిక',
    location: 'స్థానం',
    jobType: 'ఉద్యోగ రకం',
    experience: 'అవసరమైన అనుభవం',
    filter: 'ఫిల్టర్',
    applyNow: 'ఇప్పుడు దరఖాస్తు చేయండి',
    saved: 'సేవ్ చేయబడింది',
    saveJob: 'ఉద్యోగాన్ని సేవ్ చేయండి',
    unsaveJob: 'ఉద్యోగాన్ని తీసివేయండి',
    matchScore: 'మ్యాచ్ స్కోర్',
    verifiedJob: 'ధృవీకరించిన ఉద్యోగం',
    learnMore: 'మరిన్ని తెలుసుకోండి',
    exploreJobs: 'ఉద్యోగాలను అన్వేషించండి',
    postJob: 'ఉద్యోగం పోస్ట్ చేయండి',
    viewProfile: 'ప్రొఫైల్‌ని చూడండి',
    editProfile: 'ప్రొఫైల్ సవరించు',
    myApplications: 'నా దరఖాస్తులు',
    languageNoBarrier: 'భాష అడ్డంకి కాదు',
    translateDesc: 'మీ స선హితమైన భాషలో ఉద్యోగ వివరణలు, దరఖాస్తులు మరియు సంचారాన్ని అర్థం చేసుకోండి.',
    instantTranslation: 'తక్షణ అనువాదం',
    multiLanguage: 'బహుభాషా',
    accurate: 'ఖచ్చితమైన',
    aiPowered: 'AI ద్వారా నడిపిన',
  },
  ml: {
    dashboard: 'ഡാഷ്ബോർഡ്',
    jobs: 'ജോലികൾ',
    profile: 'പ്രോഫൈൽ',
    translate: 'AI വിവർത്തനം',
    home: 'ഹോം',
    features: 'ഫീച്ചറുകൾ',
    about: 'കുറിച്ച്',
    logout: 'ലോഗ് ഔട്ട്',
    login: 'ലോഗിൻ ചെയ്യുക',
    signup: 'സൈൻ അപ്പ് ചെയ്യുക',
    bridgehire: 'ബ്രിഡ്ജ് ഹയർ',
    searchJobs: 'ജോലികൾ തിരയുക',
    jobTitle: 'ജോലിയുടെ പേര്',
    location: 'സ്ഥാനം',
    jobType: 'ജോലിയുടെ തരം',
    experience: 'ആവശ്യമായ അനുഭവം',
    filter: 'ഫിൽറ്റർ',
    applyNow: 'ഇപ്പോൾ അപേക്ഷിക്കുക',
    saved: 'സംരക്ഷിച്ചത്',
    saveJob: 'ജോലി സംരക്ഷിക്കുക',
    unsaveJob: 'ജോലി നീക്കം ചെയ്യുക',
    matchScore: 'മെച്ച് സ്കോർ',
    verifiedJob: 'സ്ഥിരീകരിച്ച ജോലി',
    learnMore: 'കൂടുതലറിയുക',
    exploreJobs: 'ജോലികൾ പര്യവേക്ഷണം ചെയ്യുക',
    postJob: 'ജോലി പോസ്റ്റ് ചെയ്യുക',
    viewProfile: 'പ്രോഫൈൽ കാണുക',
    editProfile: 'പ്രോഫൈൽ എഡിറ്റ് ചെയ്യുക',
    myApplications: 'എന്റെ അപേക്ഷകൾ',
    languageNoBarrier: 'ഭാഷ തടസ്സമല്ല',
    translateDesc: 'നിങ്ങളുടെ ഇഷ്ടപ്പെട്ട ഭാഷയിൽ ജോലിയുടെ വിവരണങ്ങൾ, അപേക്ഷകൾ, ആശയവിനിമയം മനസ്സിലാക്കുക.',
    instantTranslation: 'തൽക്ഷണ വിവർത്തനം',
    multiLanguage: 'ബഹുഭാഷ',
    accurate: 'കൃത്യമായ',
    aiPowered: 'AI നിയോഗിത',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    jobs: 'ಉದ್ಯೋಗಗಳು',
    profile: 'ಪ್ರೋಫೈಲ್',
    translate: 'AI ಅನುವಾದ',
    home: 'ಹೋಮ್',
    features: 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    about: 'ಬಗ್ಗೆ',
    logout: 'ಲಾಗ್ ಔಟ್',
    login: 'ಲಾಗಿನ್ ಮಾಡಿ',
    signup: 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    bridgehire: 'ಬ್ರಿಡ್ಜ್‌ಹೈರ್',
    searchJobs: 'ಉದ್ಯೋಗಗಳನ್ನು ಹುಡುಕಿ',
    jobTitle: 'ಉದ್ಯೋಗ ಶೀರ್ಷಿಕೆ',
    location: 'ಸ್ಥಳ',
    jobType: 'ಉದ್ಯೋಗ ಪ್ರಕಾರ',
    experience: 'ಅಗತ್ಯ ಅನುಭವ',
    filter: 'ಫಿಲ್ಟರ್',
    applyNow: 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    saved: 'ಉಳಿಸಲಾಗಿದೆ',
    saveJob: 'ಉದ್ಯೋಗವನ್ನು ಉಳಿಸಿ',
    unsaveJob: 'ಉದ್ಯೋಗವನ್ನು ತೆಗೆದುಹಾಕಿ',
    matchScore: 'ಮ್ಯಾಚ್ ಸ್ಕೋರ್',
    verifiedJob: 'ಪರಿಶೀಲಿತ ಉದ್ಯೋಗ',
    learnMore: 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
    exploreJobs: 'ಉದ್ಯೋಗಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    postJob: 'ಉದ್ಯೋಗವನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ',
    viewProfile: 'ಪ್ರೋಫೈಲ್ ನೋಡಿ',
    editProfile: 'ಪ್ರೋಫೈಲ್ ಸಂಪಾದಿಸಿ',
    myApplications: 'ನನ್ನ ಅರ್ಜಿಗಳು',
    languageNoBarrier: 'ಭಾಷೆ ಯಾವುದೇ ತೊಂದರೆ ಅಲ್ಲ',
    translateDesc: 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯಲ್ಲಿ ಉದ್ಯೋಗ ವಿವರಣೆಗಳು, ಅರ್ಜಿಗಳು ಮತ್ತು ಸಂವಹನವನ್ನು ಅರ್ಥ ಮಾಡಿಕೊಳ್ಳಿ.',
    instantTranslation: 'ತಕ್ಷಣ ಅನುವಾದ',
    multiLanguage: 'ಬಹು-ಭಾಷೆ',
    accurate: 'ನಿಖುದ',
    aiPowered: 'AI ನಿಯೋಜಿತ',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    jobs: 'नोकरीया',
    profile: 'प्रोफाइल',
    translate: 'एआই अनुवादक',
    home: 'होम',
    features: 'वैशिष्ट्ये',
    about: 'बद्दल',
    logout: 'लॉगआउट',
    login: 'लॉगिन करा',
    signup: 'साइन अप करा',
    bridgehire: 'ब्रिजहायर',
    searchJobs: 'नोकरी शोधा',
    jobTitle: 'नोकरीचे शीर्षक',
    location: 'स्थान',
    jobType: 'नोकरीचा प्रकार',
    experience: 'आवश्यक अनुभव',
    filter: 'फिल्टर',
    applyNow: 'आत्ता अर्ज करा',
    saved: 'साठविले',
    saveJob: 'नोकरी साठवा',
    unsaveJob: 'नोकरी हटवा',
    matchScore: 'मिळ स्कोर',
    verifiedJob: 'सत्यापित नोकरी',
    learnMore: 'आणखी जाणून घ्या',
    exploreJobs: 'नोकरीयांचे अन्वेषण करा',
    postJob: 'नोकरी पोस्ट करा',
    viewProfile: 'प्रोफाइल पहा',
    editProfile: 'प्रोफाइल संपादित करा',
    myApplications: 'माझे अर्ज',
    languageNoBarrier: 'भाषा कोणतीही अडचण नाही',
    translateDesc: 'आपली पसंदीची भाषा नोकरीचे वर्णन, अर्ज आणि संप्रेषणे समजा।',
    instantTranslation: 'तात्काळ अनुवाद',
    multiLanguage: 'बहु-भाषा',
    accurate: 'अचूक',
    aiPowered: 'एआই द्वारे संचालित',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    jobs: 'નોકરીઓ',
    profile: 'પ્રોફાઇલ',
    translate: 'AI અનુવાદ',
    home: 'હોમ',
    features: 'વિશેષતાઓ',
    about: 'વિશે',
    logout: 'લૉગઆઉટ',
    login: 'લૉગઇન કરો',
    signup: 'સાઇન અપ કરો',
    bridgehire: 'બ્રિજહાયર',
    searchJobs: 'નોકરીઓ શોધો',
    jobTitle: 'નોકરીનું શીર્ષક',
    location: 'સ્થાન',
    jobType: 'નોકરીનો પ્રકાર',
    experience: 'આવશ્યક અનુભવ',
    filter: 'ફિલ્ટર',
    applyNow: 'અત્યારે અરજી કરો',
    saved: 'સાચવેલું',
    saveJob: 'નોકરી સાચવો',
    unsaveJob: 'નોકરી દૂર કરો',
    matchScore: 'મેચ સ્કોર',
    verifiedJob: 'ચકાસાયેલી નોકરી',
    learnMore: 'વધુ જાણો',
    exploreJobs: 'નોકરીઓ તપાસો',
    postJob: 'નોકરી પોસ્ટ કરો',
    viewProfile: 'પ્રોફાઇલ જુઓ',
    editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
    myApplications: 'મારી અરજીઓ',
    languageNoBarrier: 'ભાષા કોઈ અવરોધ નથી',
    translateDesc: 'તમારી પસંદની ભાષામાં નોકરીના વર્ણન, અરજીઓ અને સંચારણો સમજો.',
    instantTranslation: 'તાત્કાલિક અનુવાદ',
    multiLanguage: 'બહુ-ભાષા',
    accurate: 'સચોટ',
    aiPowered: 'AI દ્વારા સંચાલિત',
  },
}
